name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew shadowJar
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            wcpelib-bukkit/build/libs/
            wcpelib-nukkit/build/libs/
            wcpelib-bungeecord/build/libs/